#!/usr/bin/env python3
"""Generate src/core/term/emoji_text_default.rs from the UCD emoji-data.txt.

usage: gen_emoji_table.py <emoji-data.txt> [out.rs]

Emits the code points with Emoji=Yes and Emoji_Presentation=No: characters
that are text by default and become an emoji (2 cells) only when followed by
U+FE0F VARIATION SELECTOR-16.
"""
import re
import sys

src = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else "src/core/term/emoji_text_default.rs"
version = "unknown"
emoji, pres = set(), set()
for line in open(src, encoding="utf-8"):
    m = re.match(r"#\s*(?:emoji-data-(\S+)\.txt|Version:\s*(\S+))", line)
    if m:
        version = m.group(1) or m.group(2)
    body = line.split("#")[0].strip()
    if not body:
        continue
    rng, prop = [x.strip() for x in body.split(";")]
    a, *b = rng.split("..")
    a = int(a, 16)
    b = int(b[0], 16) if b else a
    for cp in range(a, b + 1):
        if prop == "Emoji":
            emoji.add(cp)
        elif prop == "Emoji_Presentation":
            pres.add(cp)
runs = []
for cp in sorted(emoji - pres):
    if runs and cp == runs[-1][1] + 1:
        runs[-1][1] = cp
    else:
        runs.append([cp, cp])
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("//! Generated by tools/gen_emoji_table.py from emoji-data.txt "
            f"(Unicode {version}). Do not edit.\n//!\n"
            "//! Code points with Emoji=Yes and Emoji_Presentation=No: text by\n"
            "//! default, emoji presentation (two cells) only with U+FE0F.\n\n"
            "pub(crate) static TEXT_DEFAULT_EMOJI: &[(u32, u32)] = &[\n")
    for a, b in runs:
        f.write(f"    (0x{a:04X}, 0x{b:04X}),\n")
    f.write("];\n")
print(f"{out}: {len(runs)} ranges, Unicode {version}")
